### ISSUE TITLE
A bug in the train code?

### ISSUE THREAD

**Issue by huangqiusheng** [royorel/StyleSDF#7]
I try to run train_volume_renderer.py, but the error is as follows:
`  0%|                                                 | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/3D/StyleSDF/train_volume_renderer.py", line 393, in <module>
    train(opt.training, opt.experiment, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "/3D/StyleSDF/train_volume_renderer.py", line 72, in train
    sdf, target_values = g_module.init_forward(noise, cam_extrinsics, focal, near, far)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Generator' object has no attribute 'init_forward'`
So I changed the code to`g_module.forward(noise, cam_extrinsics, focal, near, far)`, But still doesn't work. I noticed this part `loss = F.l1_loss(sdf, target_values)` , since I don't know the purpose of this, I don't know how to modify it.

**Comment by royorel** [comment]
Hi @huangqiusheng,

You are correct, I forgot to add the init_forward function to the public version of the code :)
I have now added it in commit 0bd8741. The training code should work now with no changes.

Regardless, you should download the pre-trained models which also contain the pre-trained sphere init model. When sphere initialized model is present, the code skips the initialization part. That would save you about 30 minutes from the training time.

Thank you for catching this!!

**Comment by huangqiusheng** [comment]
Thanks to the author for the prompt reply. I have another problem when I train on multiple GPUs. When using multiple gpus, I still can't increase the batch size because the memory of all gpus is full. The training parameters are the same as single gpu training. And the training speed has not improved. Here is my training command: `python -m torch.distributed.launch --nproc_per_node 4 train_volume_renderer.py --batch 8 --chunk 4 --expname compcars_sdf_vol_renderer --dataset_path /dataset/CompCars/data/img_sdf` 
one gpu: `python train_volume_renderer.py --batch 8 --chunk 4 --expname compcars_sdf_vol_renderer --dataset_path /dataset/CompCars/data/img_sdf`

**Comment by richardburleigh** [comment]
I believe the batch sizes are per GPU, not total. You can validate through nvidia-smi
